service: contentful-circular-route-detector
frameworkVersion: '2'
custom:
  bucketBaseName: serverless-shared-bucket
  ResearchHub: ${self:service}
  BusinessService: Faculty of Science
  Department: Centre for eResearch
  ProjectCode: N/A
  WikiLink: https://wiki.auckland.ac.nz/display/APPLCTN/Research+Hub
  Application: ${self:service}
  CostCentre: N/A
  Faculty: Science
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'} # Deploy with sls deploy --stage STAGE (default dev)
  region: ap-southeast-2
  endpointType: regional
  role: myDefaultRole
  tags:
    ResearchHub: ${self:custom.ResearchHub}
    BusinessService: ${self:custom.BusinessService}
    Department: ${self:custom.Department}
    ProjectCode: ${self:custom.ProjectCode}
    WikiLink: ${self:custom.WikiLink}
    Application: ${self:custom.Application}
    CostCentre: ${self:custom.CostCentre}
    Faculty: ${self:custom.Faculty}
  stackTags:
    ResearchHub: ${self:custom.ResearchHub}
    BusinessService: ${self:custom.BusinessService}
    Department: ${self:custom.Department}
    ProjectCode: ${self:custom.ProjectCode}
    WikiLink: ${self:custom.WikiLink}
    Application: ${self:custom.Application}
    CostCentre: ${self:custom.CostCentre}
    Faculty: ${self:custom.Faculty}
  deploymentBucket:
    name: ${self:custom.bucketBaseName}-test
  apiGateway:
    apiKeySourceType: HEADER
  apiKeys:
    - name: ${self:service}-${self:provider.stage}-apiKey

# you can define service wide environment variables here
# environment:
#   variable1: value1
    
package:
  exclude:
    - .git/**
    - .gitignore
    - .vscode/*
    - package.json
    - package-lock.json
    - README.md
    - serverless.yml

functions:
  detect-circular:
    handler: handler.main
    events:
      # can be invoked via api gateway. Pass in the graphql server domain you want to test against.
      - http:
          path: /{graphqlserverdomain}
          method: get
          cors:
            true
          private: true
      # Scheduled triggers, to test each of the three Contentful environments (dev/test/prod)
      - schedule:
          rate: rate(1 hour)
          input:
            graphqlServerDomain: rhubcpapi.auckland.ac.nz
      - schedule:
          rate: rate(1 hour)
          input:
            graphqlServerDomain: rhubcpapi.connect.test.amazon.auckland.ac.nz
      - schedule:
          rate: rate(1 hour)
          input:
            graphqlServerDomain: rhubcpapi-dev.connect.test.amazon.auckland.ac.nz

plugins:
  - serverless-offline

resources:
 Resources:
    myDefaultRole:
      Type: "AWS::IAM::Role"
      Properties:
        Path: /
        RoleName: ${self:service}-lambda-role-${self:provider.stage}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: "sts:AssumeRole"
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:logs"
                          - Ref: "AWS::Region"
                          - Ref: "AWS::AccountId"
                          - "log-group:/aws/lambda/*:*:*"
